---

namespace: 'oxlorg'
name: 'nftables'
version: 1.0.4
readme: 'README.md'
authors:
  - 'OXL IT Services <contact+nftables@oxl.at>'
description: "Ansible Collection to manage NFTables firewalls"
license_file: 'LICENSE.txt'
tags:
  - 'firewall'
  - 'nftables'
  - 'linux'
  - 'iac'
  - 'network'
  - 'security'
  - 'filter'
dependencies: {}
repository: 'https://github.com/O-X-L/ansible-collection-nftables'
documentation: 'https://ansible-nftables.oxl.app'
homepage: 'https://www.OXL.at'
issues: 'https://github.com/O-X-L/ansible-collection-nftables/issues'
build_ignore: [
  '*_pytest.py', '*_testdata.py', '*pytest_cache', '*/_tmpl.py',
  '.**', 'pytest.ini', 'requirements_*.txt',
  'docs**', 'scripts**', 'venv**', 'Makefile', 'legacy**',
]
