---

name: Unit Tests

on:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt
        shell: bash

      - name: Running Tests
        run: python3 -m pytest
        shell: bash
